name: .NET Core

on:
  push:
    branches: [ main, vnext ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
     matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
      working-directory: Kryptos
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Kryptos
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Kryptos
    - name: Pack
      run: dotnet pack --configuration Release
      working-directory: Kryptos
